export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_START = "FETCH_EMPLOYEES_START";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAIL = "FETCH_EMPLOYEES_FAIL";
export const CLEAR_EMPLOYEE_STATE = "CLEAR_EMPLOYEE_STATE";
